# Generated by Django 2.2.2 on 2019-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('host_attend_events', models.BooleanField(default=False)),
                ('knock_on_doors', models.BooleanField(default=False)),
                ('make_calls', models.BooleanField(default=False)),
                ('send_texts', models.BooleanField(default=False)),
                ('donate_skills', models.BooleanField(default=False)),
                ('pledge_to_donate', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
